### ISSUE TITLE
Introduce a consistent error management policy.

### ISSUE THREAD

**Issue by fpacifici** [getsentry/rust_arroyo#13]
In this library there is no consistent way to define errors in a way that can be propagated. Most of the times we just drop every useful information. 

The first goal is to read about how to create errors in Rust
https://doc.rust-lang.org/book/ch09-00-error-handling.html
https://www.lpalmieri.com/posts/error-handling-rust/
see what relay and symbolicator do
ask in discuss-rust 

Then decide how to organize errors in the library: how do we break them down logically? Should we have a ConsumerError large enum with all the cases and use that everywhere? Should we have multiple categories (multiple enums) ?

Then start replacing the ad-hoc errors (which are now defined basically per method) everywhere

I call this a first task because it is mostly about learning how to do errors management in rust, then the changes to the library should not be too substantial

**Comment by lynnagara** [comment]
There may be some follow up to do but the overall strategy for error handling was done in https://github.com/getsentry/rust_arroyo/pull/23
